/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as MonthlyReportRouteImport } from './routes/monthly-report'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeviceIdRouteImport } from './routes/device.$id'

const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyReportRoute = MonthlyReportRouteImport.update({
  id: '/monthly-report',
  path: '/monthly-report',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceIdRoute = DeviceIdRouteImport.update({
  id: '/device/$id',
  path: '/device/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/executive': typeof ExecutiveRoute
  '/login': typeof LoginRoute
  '/monthly-report': typeof MonthlyReportRoute
  '/overview': typeof OverviewRoute
  '/risk': typeof RiskRoute
  '/device/$id': typeof DeviceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/executive': typeof ExecutiveRoute
  '/login': typeof LoginRoute
  '/monthly-report': typeof MonthlyReportRoute
  '/overview': typeof OverviewRoute
  '/risk': typeof RiskRoute
  '/device/$id': typeof DeviceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/executive': typeof ExecutiveRoute
  '/login': typeof LoginRoute
  '/monthly-report': typeof MonthlyReportRoute
  '/overview': typeof OverviewRoute
  '/risk': typeof RiskRoute
  '/device/$id': typeof DeviceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/executive'
    | '/login'
    | '/monthly-report'
    | '/overview'
    | '/risk'
    | '/device/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/executive'
    | '/login'
    | '/monthly-report'
    | '/overview'
    | '/risk'
    | '/device/$id'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/executive'
    | '/login'
    | '/monthly-report'
    | '/overview'
    | '/risk'
    | '/device/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  ExecutiveRoute: typeof ExecutiveRoute
  LoginRoute: typeof LoginRoute
  MonthlyReportRoute: typeof MonthlyReportRoute
  OverviewRoute: typeof OverviewRoute
  RiskRoute: typeof RiskRoute
  DeviceIdRoute: typeof DeviceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly-report': {
      id: '/monthly-report'
      path: '/monthly-report'
      fullPath: '/monthly-report'
      preLoaderRoute: typeof MonthlyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/$id': {
      id: '/device/$id'
      path: '/device/$id'
      fullPath: '/device/$id'
      preLoaderRoute: typeof DeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  ExecutiveRoute: ExecutiveRoute,
  LoginRoute: LoginRoute,
  MonthlyReportRoute: MonthlyReportRoute,
  OverviewRoute: OverviewRoute,
  RiskRoute: RiskRoute,
  DeviceIdRoute: DeviceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
